name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install
      - run: pnpm turbo run build
      - run: pnpm publish:api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
